name: WF DEVSECOPS END-TO-END
run-name: RUNNER DEVSECOPS END-TO-END
on: 
  push:
    branches: ['master']
jobs:
  job-sast:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
      - name: Check out the repo (MAIN-D)
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Set up JDK 11 (MAIN-D)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven cloud (MAIN-P)[SAST]
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=yagami-escobar_devsecops-github-actions-all -Dsonar.organization=bcodex1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  job-sca:
    runs-on: ubuntu-latest
    needs: job-sast
    if: success()
    name: Run the SCA scan on the source code
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  job-dast:
    runs-on: ubuntu-latest
    needs: job-sca
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
